version: '3'
services:
    apidb:
        image: 'mariadb'
        restart: 'always'
        environment:              
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'apidb'
            MYSQL_USER: 'appuser'
            MYSQL_PASSWORD: 'password'
        networks: ['backend']
        ports:
            - '3307:3306'
    authdb:
        image: 'mariadb'
        restart: 'always'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'authdb'
            MYSQL_USER: 'appuser'
            MYSQL_PASSWORD: 'password'
        networks: ['backend']
        ports:
            - '3308:3306'
networks:
    backend:
        driver: 'bridge'